server:
  port: 80

spring.jpa:
  open-in-view: false
  database:
  properties:
    hibernate:
      jdbc.lob.non_contextual_creation: true
      jdbc.time_zone: UTC
      temp.use_jdbc_metadata_defaults=false: false
      show_sql: true
      format_sql: true
  hibernate:
    ddl-auto: validate

spring.datasource:
  url:
  username:
  password:
